import {
  AutodeskIcon,
  BitbucketIcon,
  BlenderIcon,
  CanvaIcon,
  ClaudeIcon,
  CssIcon,
  CursorIcon,
  DockerIcon,
  FigmaIcon,
  FirebaseIcon,
  GithubIcon,
  GitlabIcon,
  GsapIcon,
  HtmlIcon,
  JavaIcon,
  JavascriptIcon,
  LaravelIcon,
  MongodbIcon,
  MysqlIcon,
  NextjsIcon,
  NodejsIcon,
  NpmIcon,
  PhotoshopIcon,
  PhpIcon,
  PostgresqlIcon,
  PythonIcon,
  ReactIcon,
  ReactNativeIcon,
  ReduxIcon,
  SanityIcon,
  SassIcon,
  TailwindIcon,
  ThreejsIcon,
  TypescriptIcon,
  WordpressIcon,
} from './Icons';

type IconType = React.FC<React.SVGProps<SVGSVGElement>>;

/** Canonical label → Icon component. Superset of all tech icons used across the app. */
export const techIconMap: Record<string, IconType> = {
  HTML5: HtmlIcon,
  CSS3: CssIcon,
  TypeScript: TypescriptIcon,
  React: ReactIcon,
  'Next.js': NextjsIcon,
  'React Native': ReactNativeIcon,
  Redux: ReduxIcon,
  'Three.js': ThreejsIcon,
  TailwindCSS: TailwindIcon,
  Sass: SassIcon,
  GSAP: GsapIcon,
  PHP: PhpIcon,
  'Node.js': NodejsIcon,
  Java: JavaIcon,
  Python: PythonIcon,
  Laravel: LaravelIcon,
  Wordpress: WordpressIcon,
  Sanity: SanityIcon,
  MySQL: MysqlIcon,
  Firebase: FirebaseIcon,
  MongoDB: MongodbIcon,
  PostgreSQL: PostgresqlIcon,
  Photoshop: PhotoshopIcon,
  '3Ds Max': AutodeskIcon,
  Blender: BlenderIcon,
  Figma: FigmaIcon,
  Canva: CanvaIcon,
  Docker: DockerIcon,
  GitHub: GithubIcon,
  CursorAI: CursorIcon,
  Claude: ClaudeIcon,
  npm: NpmIcon,
  // Aliases — extra labels used in experience stack arrays
  'Vanilla JS': JavascriptIcon,
  Git: GithubIcon,
  'Sanity CMS': SanityIcon,
  GitLab: GitlabIcon,
  Bitbucket: BitbucketIcon,
};

/** Category grouping for the Technos section. Values are keys into techIconMap. */
export const techCategoryGroups: Record<string, string[]> = {
  frontend: [
    'HTML5',
    'CSS3',
    'TypeScript',
    'React',
    'Next.js',
    'React Native',
    'Redux',
    'Three.js',
    'TailwindCSS',
    'Sass',
    'GSAP',
  ],
  backend: [
    'Python',
    'PHP',
    'Node.js',
    'Java',
    'Laravel',
    'Wordpress',
    'Sanity',
  ],
  database: ['MySQL', 'MongoDB', 'Firebase', 'PostgreSQL'],
  design: ['Photoshop', '3Ds Max', 'Blender', 'Figma', 'Canva'],
  tools: ['Docker', 'GitHub', 'CursorAI', 'Claude', 'npm'],
};

/** Flat ordered list for the resume skills section. */
export const resumeTechList: string[] = [
  'HTML5',
  'CSS3',
  'TypeScript',
  'React',
  'Next.js',
  'React Native',
  'Redux',
  'Three.js',
  'TailwindCSS',
  'Sass',
  'GSAP',
  'PHP',
  'Node.js',
  'Java',
  'Python',
  'Laravel',
  'Wordpress',
  'Sanity',
  'MySQL',
  'Firebase',
  'MongoDB',
  'Photoshop',
  '3Ds Max',
  'Blender',
  'Canva',
  'Figma',
  'Docker',
  'GitHub',
  'CursorAI',
  'npm',
];
